# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the project files
COPY . .

# Build the project
RUN npm run build

# Streamable HTTP MCP (remote clients, tunnels). Override CMD for stdio: node build/index.js
EXPOSE 8787
ENV MCP_HTTP_HOST=0.0.0.0
ENV MCP_HTTP_PORT=8787

# Set environment variables from Docker if desired (they can also be set externally)
# ENV METABASE_URL=https://your-metabase-instance.com \
#     METABASE_USERNAME=your_username \
#     METABASE_PASSWORD=your_password

CMD ["node", "build/http.js"]
